Repository Team-501-The-PowerKnights/2022-robot, pull requests merged in 2022-03, with the labels that each got.

#47 Climber automation
  src/main/java/frc/robot/commands/climber/ClimberClimbTimed.java
  src/main/java/frc/robot/commands/climber/ClimberClimbToLimit.java
  src/main/java/frc/robot/commands/climber/ClimberExtendToLimit.java
  src/main/java/frc/robot/commands/climber/ClimberRunToLimit.java
  src/main/java/frc/robot/hmi/OperatorGamepad.java
  src/main/java/frc/robot/subsystems/climber/BaseClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/ClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/IClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/StubClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/ZesterClimberSubsystem.java
  src/main/java/frc/robot/telemetry/TelemetryNames.java
Labels: enhancement

#75 Fix Where All Names Come From
  src/main/java/frc/robot/config/BuildVersionInfo.java
  src/main/java/frc/robot/modules/ModuleNames.java
  src/main/java/frc/robot/modules/pcm/BasePCMModule.java
  src/main/java/frc/robot/modules/pdp/BasePDPModule.java
  src/main/java/frc/robot/sensors/SensorNames.java
  src/main/java/frc/robot/sensors/elevator/BaseElevatorSensor.java
  src/main/java/frc/robot/sensors/gyro/BaseGyroSensor.java
  src/main/java/frc/robot/sensors/incrementer/BaseIncrementerSensor.java
  src/main/java/frc/robot/sensors/turretlocation/BaseTurretLocationSensor.java
  src/main/java/frc/robot/sensors/vision/BaseVisionSensor.java
  src/main/java/frc/robot/subsystems/SubsystemNames.java
  src/main/java/frc/robot/telemetry/TelemetryNames.java
Labels: change req

#76 Spark error checking
  src/main/java/frc/robot/subsystems/climber/ClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/ZesterClimberSubsystem.java
  src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/ProtoDriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/ZesterDriveSubsystem.java
  src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java
  src/main/java/frc/robot/subsystems/shooter/ZesterShooterSubsystem.java
  src/main/java/frc/robot/subsystems/turret/TurretSubsystem.java
  src/main/java/frc/robot/subsystems/turret/ZesterTurretSubsystem.java
Labels: change req

#81 Finish Implementation of F310 Gamepad
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/config/BuildVersionInfo.java
  src/main/java/frc/robot/hmi/DriverGamepad.java
  src/main/java/frc/robot/hmi/F310Gamepad.java
  src/main/java/frc/robot/hmi/OperatorGamepad.java
Labels: change req

#84 Trajectory generation
  .SysId/sysid.json
  src/main/deploy/output/StraightLine.wpilib.json
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/drive/DriveTrajectory.java
  src/main/java/frc/robot/config/BuildVersionInfo.java
  src/main/java/frc/robot/sensors/gyro/SuitcaseGyroSensor.java
  src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/IDriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/ProtoDriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/StubDriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/SuitcaseDriveSubsystem.java
  src/main/java/frc/robot/subsystems/drive/ZesterDriveSubsystem.java
Labels: enhancement

#94 Custom trajectories
  PathWeaver/Autos/1BallHangarSide
  PathWeaver/Paths/HangarSideFirstBall
  PathWeaver/Paths/LinearTest
  PathWeaver/Paths/NonLinearTest
  PathWeaver/pathweaver.json
  src/main/deploy/output/HangarSideFirstBall.wpilib.json
  src/main/deploy/output/LinearTest.wpilib.json
  src/main/deploy/output/NonLinearTest.wpilib.json
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/drive/DriveTrajectory.java
  src/main/java/frc/robot/config/BuildVersionInfo.java
  src/main/java/frc/robot/sensors/gyro/GyroSensor.java
  src/main/java/frc/robot/sensors/gyro/SuitcaseGyroSensor.java
  src/main/java/frc/robot/sensors/vision/LimelightVision.java
  src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java
Labels: enhancement, tuning

#96 Climber state impl
  src/main/java/frc/robot/commands/ClimbFloorToLevel2Pose.java
  src/main/java/frc/robot/commands/ClimbLevel2ToLevel3Pose.java
  src/main/java/frc/robot/commands/ClimbLevel3ToLevel4Pose.java
  src/main/java/frc/robot/commands/ClimbSetSubystemsPose.java
  src/main/java/frc/robot/commands/climber/ClimberClimb.java
  src/main/java/frc/robot/commands/climber/ClimberClimbTimed.java
  src/main/java/frc/robot/commands/climber/ClimberExtendElbowToLimit.java
  src/main/java/frc/robot/commands/climber/ClimberExtendLevel2.java
  src/main/java/frc/robot/commands/climber/ClimberExtendShoulderToLimit.java
  src/main/java/frc/robot/commands/climber/ClimberRetract.java
  src/main/java/frc/robot/commands/climber/ClimberRetractInPits.java
  src/main/java/frc/robot/commands/climber/ClimberRunToTarget.java
  src/main/java/frc/robot/commands/climber/ClimberStateMachine.java
  src/main/java/frc/robot/commands/turret/TurretHome.java
  src/main/java/frc/robot/subsystems/climber/BaseClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/ClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/IClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/StubClimberSubsystem.java
  src/main/java/frc/robot/subsystems/climber/ZesterClimberSubsystem.java
  src/main/java/frc/robot/telemetry/TelemetryNames.java
Labels: enhancement
