Repository Team-501-The-PowerKnights/2022-robot, pull requests merged in 2022-02, with the labels that each got.

#1 feat: have deploy task depend on writeBuildInfo
  build.gradle
Labels: enhancement

#4 javadoc generation
  build.gradle
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/IIandTCommand.java
  src/main/java/frc/robot/config/BuildVersionInfo.java
  src/main/java/frc/robot/subsystems/drive/IDriveSubsystem.java
  src/main/java/frc/robot/subsystems/package-info.java
Labels: enhancement

#12 Update Documentation
  config_dash/proto/shuffleboard.json
  config_dash/real/shuffleboard.json
  config_dash/suitcase/shuffleboard.json
  config_dash/zester/shuffleboard.json
  electrical_desc.md
Labels: documentation

#27 feat: correct writeBuildInfo task def
  build.gradle
  src/main/java/frc/robot/config/BuildVersionInfo.java
Labels: bug
